csv_app/urls.py
from django.conf import settings
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static


urlpatterns = [
    path('', include('schemas.urls')),
    re_path(r'^celery-progress/', include('celery_progress.urls')),

    path('login/',
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'),

    path('logout/',
         auth_views.LogoutView.as_view(),
         name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'schemas.front.views.handler404'
handler500 = 'schemas.front.views.handler500'

schemas/urls.py
from django.urls import path

from .front import views

app_name = "schemas"


urlpatterns = [
    path('', views.SchemasList.as_view(), name='schemas'),
    path('schemas/', views.SchemasList.as_view(), name='schemas'),
    path('create/', views.CreateSchemaView.as_view(), name='create'),
    path('<int:pk>/edit', views.UpdateSchema.as_view(), name='edit'),
    path('<int:pk>/delete/', views.DeleteSchema.as_view(), name='delete'),

    path('data_sets/', views.DataSetsListView.as_view(), name='data_sets'),
    path('generate_files/', views.GenerateView.as_view(), name='generate'),
    path('<int:pk>/download/', views.DownloadView.as_view(), name='download'),
]

schemas/core/models/column.py
# -*- coding: utf-8 -*-
from __future__ import annotations
# External
from django.db import models
# Internal
from ..builder import SCHEMA
from .schema import Schema
# Typing
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ..builder.structures import UnionColumns


class Column(models.Model):

    schema = models.ForeignKey(Schema, on_delete=models.CASCADE)
    name = models.CharField(max_length=400)
    type = models.CharField(max_length=400,
                            choices=SCHEMA.COLUMN_CHOICES,
                            default=SCHEMA.COLUMN_CHOICES[0][0])
    min = models.IntegerField(null=True)
    max = models.IntegerField(null=True)
    order = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f'Column: {self.name}'

    def to_dataclass(self) -> UnionColumns:
        """
        Convert column to dataclass for building csv file.
        """
        dc = SCHEMA.COLUMN_TYPES.get(self.type)
        if dc:
            args = dict(header=self.name)
            dc_fields = dc.__dataclass_fields__
            if 'character' in dc_fields:
                args['character'] = self.schema.str_character

            if 'min' in dc_fields and 'max' in dc_fields:
                if self.min:
                    args['min'] = self.min
                if self.max:
                    args['max'] = self.max
            dc = dc(**args)
        return dc

schemas/core/models/task.py
from django.db import models


class Task(models.Model):
    """
    Table for current reserved and active tasks.
    todo: remove table and find way to get schema id from AsyncResult object.
    """
    task_id = models.CharField(max_length=1000)
    schema_id = models.IntegerField()
    group_id = models.TextField()  # Same as admin user id but in str type.

    # Need to buy pycharm pro version and remove next line.
    objects = models.Manager()

    def __str__(self):
        return f'{self.task_id} ({self.schema_id})'

schemas/front/forms/column.py
# External
from django import forms
# Internal
from ...core.models import Column
from ...core.builder import SCHEMA


_FORM_INPUT_ATTR = {
    'class': 'form-control'
}


class ColumnForm(forms.ModelForm):

    type_field_attrs = {
        "onChange": 'addFields(this, ''"{{ ranged_types }}")'
    }

    name = forms.CharField(label='Column name',
                           required=True,
                           max_length=300)

    type = forms.ChoiceField(label='Column type',
                             required=True,
                             initial=SCHEMA.COLUMN_CHOICES[0][0],
                             choices=SCHEMA.COLUMN_CHOICES,
                             widget=forms.Select(attrs=type_field_attrs))

    min = forms.IntegerField(label='From',
                             required=False,
                             initial=1)

    max = forms.IntegerField(label='To',
                             required=False,
                             initial=1)

    class Meta:
        model = Column
        fields = ['name', 'type', 'min', 'max', 'order',
                  'schema', 'id']
        widgets = {
            'schema': forms.HiddenInput(),
            'is_ranged': forms.HiddenInput(),
            'order': forms.HiddenInput()
        }

    def __init__(self, *args, **kwargs):
        super(ColumnForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(_FORM_INPUT_ATTR)
        self.fields['type'].widget.attrs.update(_FORM_INPUT_ATTR)
        self.fields['min'].widget.attrs.update(_FORM_INPUT_ATTR)
        self.fields['max'].widget.attrs.update(_FORM_INPUT_ATTR)

schemas/front/forms/formsets.py
# External
from django import forms
from django.core.exceptions import ValidationError
from django.template.loader import render_to_string
# Internal
from .column import ColumnForm
from ...core.models import Schema, Column
from ...core.builder import SCHEMA


_FORM_INPUT_ATTR = {
    'class': 'form-control'
}


class ColumnFormSet(forms.BaseInlineFormSet):

    @property
    def templated_empty_form(self) -> str:
        """
        Return html template for empty form.
        """
        context = {'form': self.empty_form,
                   'prefix': self.prefix}
        content = render_to_string('column_form.html', context)
        return content

    def get_ordering_widget(self):
        return forms.NumberInput(attrs=_FORM_INPUT_ATTR)

    def clean(self):
        """
        Validation for columns formset.
        """

        if any(self.errors):
            return

        if len(self.forms) == len(self.deleted_forms):
            raise ValidationError('At least one column required.')

        titles = dict()
        for form in self.forms:

            if self.can_delete and self._should_delete_form(form):
                continue

            if not form.cleaned_data.get('name'):
                msg = "This field is required."
                form.add_error('name', msg)

            if form.cleaned_data.get('ORDER') is None:
                msg = "This field is required."
                form.add_error('ORDER', msg)

            # Validate that no two columns have the same name.
            title = form.cleaned_data.get('name')
            if title and title in titles:
                msg = 'Columns must have distinct names.'
                form.add_error('name', msg)
                titles[title].add_error('name', msg)
            titles[title] = form

            # Validate 'min' and 'max' fields for selected column types.
            selected_type = form.cleaned_data.get('type')
            ranged_type = SCHEMA.RANGED_TYPES_DICT.get(selected_type)

            selected_min = form.cleaned_data.get('min')
            selected_max = form.cleaned_data.get('max')

            # Check if 'min' field is required.
            if ranged_type and selected_min is None:
                msg = "This field is required."
                form.add_error('min', msg)

            # Check if 'max' field is required.
            if ranged_type and selected_max is None:
                msg = "This field is required."
                form.add_error('max', msg)

            # Check if 'min' is smaller that 'max'.
            if (selected_min is not None
                    and selected_max is not None
                    and selected_min > selected_max):
                msg = f"Minimum value can't be grater than maximum."
                form.add_error('min', msg)

            # Check 'min' field for allowed value.
            if (ranged_type
                    and ranged_type.min is not None
                    and selected_min is not None
                    and selected_min < ranged_type.min):
                msg = (f"Minimum value for the {ranged_type.name} " 
                       f"is {ranged_type.min}")
                form.add_error('min', msg)

            # Check 'max' field got allowed value.
            if (ranged_type
                    and ranged_type.max is not None
                    and selected_max is not None
                    and selected_max > ranged_type.max):
                msg = (f"Maximum value for the {ranged_type.name} "
                       f"is {ranged_type.max}")
                form.add_error('max', msg)


column_formset = forms.inlineformset_factory(
    Schema,
    Column,
    min_num=1,
    extra=0,
    can_delete=True,
    can_order=True,
    form=ColumnForm,
    formset=ColumnFormSet
)

schemas/front/forms/generate.py
from django import forms


class GenerateForm(forms.Form):
    rows = forms.IntegerField(min_value=1, required=True, initial=1)

schemas/front/forms/schema.py
# External
from django import forms
# Internal
from ...core.models import Schema
from ...core.builder import SCHEMA


_FORM_INPUT_ATTR = {
    'class': 'form-control'
}


class SchemaForm(forms.ModelForm):

    name = forms.CharField(label='Name',
                           required=True,
                           max_length=300)

    separator = forms.ChoiceField(label='Column separator',
                                  required=True,
                                  choices=SCHEMA.SEPARATOR_CHOICES)

    str_character = forms.ChoiceField(label='String character',
                                      required=True,
                                      choices=SCHEMA.CHARACTER_CHOICES)

    class Meta:
        model = Schema
        fields = ['name', 'separator', 'str_character', 'id']

    def __init__(self, *args, **kwargs):
        super(SchemaForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(_FORM_INPUT_ATTR)
        self.fields['separator'].widget.attrs.update(_FORM_INPUT_ATTR)
        self.fields['str_character'].widget.attrs.update(_FORM_INPUT_ATTR)

schemas/front/views/data_sets.py
# External
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic, View
# Internal
from django.views.generic.detail import SingleObjectMixin

from .auth import AdminRequiredMixin, SchemaPermissionMixin
from ..forms import GenerateForm
from ...core.models import Schema
from ...core.celery import task_manager


class DataSetsListView(AdminRequiredMixin,
                       generic.edit.FormMixin,
                       generic.ListView):

    model = Schema
    form_class = GenerateForm
    queryset = Schema.objects.order_by('-timestamp')
    context_object_name = 'data_sets'
    template_name = 'data_sets.html'
    paginate_by = 20

    def get_queryset(self):
        queryset = super(DataSetsListView, self).get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tasks = task_manager.get_ids(user_id=self.request.user.id)
        context['task_ids'] = sorted(tasks.items())
        return context


class GenerateView(AdminRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        """
        Generate csv file for all schemas without csv_file.
        """
        form = GenerateForm(request.GET)
        if form.is_valid():
            rows = form.cleaned_data['rows']
            task_manager.run_tasks(user_id=request.user.id, rows=rows)
        return HttpResponseRedirect(reverse_lazy('schemas:data_sets'))


class DownloadView(AdminRequiredMixin,
                   SingleObjectMixin,
                   SchemaPermissionMixin,
                   View):

    model = Schema

    def get(self, request, *args, **kwargs):
        """
        Download csv file for given schema pk.
        """
        schema = self.get_object()
        if schema.csv_file:
            response = HttpResponse(schema.csv_file,
                                    content_type='text/plain')
            content = "attachment; filename={}".format(schema.csv_file.name)
            response['Content-Disposition'] = content
            return response
        else:
            raise Http404

schemas/front/views/errors.py
# External
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy


def handler404(request, exception, template_name="errors/404.html"):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse_lazy('login'))
    else:
        response = render(request, template_name)
        response.status_code = 404
    return response


def handler500(request, template_name="errors/500.html"):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse_lazy('login'))
    else:
        response = render(request, template_name)
        response.status_code = 500
    return response

schemas/front/views/schema.py
# External
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
# Internal
from .auth import AdminRequiredMixin, SchemaPermissionMixin
from ..forms import SchemaForm, column_formset
from ...core.builder import SCHEMA
from ...core.models import Schema


__all__ = ['CreateSchemaView', 'UpdateSchema', 'SchemasList', 'DeleteSchema']


class CreateSchemaView(AdminRequiredMixin, generic.CreateView):

    model = Schema
    form_class = SchemaForm
    template_name = 'schema.html'
    title = 'New Schema'

    def get_context_data(self, **kwargs):
        context = super(CreateSchemaView, self).get_context_data(**kwargs)
        context['column_formset'] = column_formset(prefix="column")
        context['ranged_types'] = SCHEMA.RANGED_TYPES
        context['title'] = self.title
        return context

    def post(self, request, *args, **kwargs):
        schema_form = SchemaForm(request.POST)
        column_form = column_formset(request.POST, prefix="column")

        if schema_form.is_valid() and column_form.is_valid():
            # Save schema.
            schema = schema_form.save(commit=False)
            schema.user = request.user
            schema.save()
            # Save column.
            column_form.instance = schema
            _set_valid_order(column_form)
            for form in column_form.forms:
                form.instance.order = form.cleaned_data['ORDER']
            column_form.save()
            return HttpResponseRedirect(reverse_lazy('schemas:schemas'))
        else:
            context = {
                'form': schema_form,
                'column_formset': column_form,
                'ranged_types': SCHEMA.RANGED_TYPES,
                'title': self.title
            }
            return render(request, self.template_name, context)


class UpdateSchema(AdminRequiredMixin,
                   SchemaPermissionMixin,
                   generic.edit.UpdateView):

    model = Schema
    form_class = SchemaForm
    template_name = 'schema.html'
    title = 'Update Schema'
    success_url = reverse_lazy('schemas:schemas')

    def get_context_data(self, **kwargs):
        context = super(UpdateSchema, self).get_context_data(**kwargs)
        if self.request.POST:
            context['column_formset'] = column_formset(
                self.request.POST,
                instance=self.object,
                prefix="update_column")
        else:
            context['column_formset'] = column_formset(
                instance=self.object,
                prefix="update_column")

        context['ranged_types'] = SCHEMA.RANGED_TYPES
        context['title'] = self.title
        return context

    def form_valid(self, form, *args, **kwargs):
        context = self.get_context_data()
        column_form = context['column_formset']
        if column_form.is_valid():
            self.object = form.save()
            column_form.instance = self.object
            _set_valid_order(column_form)
            for form in column_form.forms:
                form.instance.order = form.cleaned_data['ORDER']
            column_form.save()
            self.object.csv_file.delete()
            return HttpResponseRedirect(self.get_success_url())
        else:
            context = {
                'form': form,
                'column_formset': column_form,
                'ranged_types': SCHEMA.RANGED_TYPES,
                'title': self.title
            }
            return render(self.request, self.template_name, context)


class SchemasList(AdminRequiredMixin, generic.ListView):

    queryset = Schema.objects.all()
    context_object_name = 'schemas'
    template_name = 'schemas.html'
    paginate_by = 20

    def get_queryset(self):
        queryset = super(SchemasList, self).get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset


class DeleteSchema(AdminRequiredMixin,
                   SchemaPermissionMixin,
                   generic.DeleteView):

    model = Schema
    template_name = 'confirm_delete_schema.html'
    success_url = reverse_lazy('schemas:schemas')


def _set_valid_order(forms):
    """
    In 'ORDER' field inputs can be random integers,
    so set correct order for columns.
    """
    forms = [form for form in forms
             if form.cleaned_data.get('ORDER') is not None]
    sorted_forms = sorted(forms, key=lambda k: k.cleaned_data.get('ORDER'))
    for order, form in enumerate(sorted_forms):
        form.cleaned_data['ORDER'] = order

schemas/front/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <!-- Internal JS -->
        <script>var rangedTypes = '{{ranged_types}}';</script>
        <script src="{% static 'js/form/add_fields.js' %}"></script>
        <script src="{% static 'js/form/add_form.js' %}"></script>
        <script src="{% static 'js/form/delete_form.js' %}"></script>
        <script src="{% static 'celery_progress/celery_progress.js' %}"></script>
        <script src="{% static 'js/progress_bar/result.js' %}"></script>
        <!-- Internal CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <!-- External CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
            integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <!-- External JS and jQuery -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
        <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
        <title>{% block title %}FakeCSV{% endblock %}</title>
    </head>

    <body>
        {% if user.is_authenticated %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light" id="navbar">
                <div class="container-fluid">

                    <div id="nav-bar-left-container">
                        <div class="collapse show navbar-collapse" id="navbarNavAltMarkup">
                            <div class="navbar-nav">
                                <a class="navbar-brand" href="{% url 'schemas:data_sets' %}" style="color: black;">FakeCSV</a>
                                <a class="nav-item nav-link active" href="{% url 'schemas:schemas' %}">Schemas</a>
                            </div>
                        </div>
                    </div>

                    <div id="nav-bar-right-container">
                        <div class="collapse show navbar-collapse">
                            <div class="navbar-nav">
                                <a class="nav-item nav-link disabled" href="#">Hello, <b>{{ user.get_username }}</b></a>
                                <a class="nav-item nav-link" href="{% url 'logout' %}?next={% url 'login' %}">Logout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        {% endif %}
        <div id="content">{% block content %}{% endblock %}</div>
    </body>
</html>

schemas/front/templates/column_form.html
<div id='column_form_wrapper-{% if form.DELETE %}{{ form.DELETE.id_for_label }}{% else %}{{ form.prefix }}-DELETE{% endif %}'>

    <div class="form-row">

        <div class="form-group col-md-3">
            {{ form.name.label }}
            {{ form.name }}
            {% if form.name.errors %}
                {% for error in form.name.errors %}
                    <div class="form-control is-invalid">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </div>

        <div class="form-group col-md-3">
            {{ form.type.label }}
            {{ form.type }}
            {% if form.type.errors %}
                {% for error in form.type.errors %}
                    <div class="form-control is-invalid">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </div>

        <div id="min-max-form-block-{{ form.type.id_for_label }}" class="{% if form.type.value in ranged_types %}visible{% else %}invisible{% endif %}">
            <div class="form-row">
                <div class="form-group col-md-3">
                    {{ form.min.label }}
                    {{ form.min }}
                </div>
                <div class="form-group col-md-3">
                    {{ form.max.label }}
                    {{ form.max }}
                </div>
            </div>

            {% if form.min.errors %}
                {% for error in form.min.errors %}
                    <div class="form-control is-invalid">{{ error }}</div>
                {% endfor %}
            {% endif %}
            {% if form.max.errors %}
                {% for error in form.max.errors %}
                    <div class="form-control is-invalid">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </div>

        <div class="form-row">
            <div class="form-group col-md-10">
                {{ form.ORDER.label }}
                {{ form.ORDER }}
                {% if form.ORDER.errors %}
                    {% for error in form.ORDER.errors %}
                        <div class="form-control is-invalid">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="form-group col-md-2">
                {% if form.DELETE %}
                    {% if prefix == 'update_column' %}
                        <!-- Generate not empty delete field for update.-->
                        {{ form.DELETE.label }} {{ form.DELETE }}
                    {% else %}
                        <!-- Generate not empty delete button for create view.-->
                        <label></label>
                        <a type="button" style="color:red;" name="{{ form.DELETE.name_for_label }}" id="{{ form.DELETE.id_for_label }}" class="btn btn-default" onclick="deleteForm('{{ prefix }}', this)">Delete</a>
                    {% endif %}
                {% else %}
                    <!-- Generate empty delete field.-->
                    <label></label>
                    <a type="button" style="color:red;" name="{{ form.prefix }}-DELETE" id="id_{{ form.prefix }}-DELETE" class="btn btn-default" onclick="deleteForm('{{ prefix }}', this)">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>
    {{ form.id }}
    {{ form.order }}
</div>

schemas/front/templates/confirm_delete_schema.html
{% extends "base.html" %}
{% block content %}
    <div class="centered">
        <form action="" method="post">
            {% csrf_token %}
            <h4>Deleting schema: <a href="{% url 'schemas:edit' schema.id %}">{{ object.name }}</a></h4>
            <h4>Are you sure?</h4>
            <input type="submit" class="btn btn-danger" value="Delete schema"/>
            <a class="btn btn-primary" href="{% url 'schemas:schemas' %}">Cancel</a>
        </form>
    </div>
{% endblock %}

schemas/front/templates/data_sets.html
{% extends "base.html" %}
{% block content %}

<div id="data-sets-list-wrapper" class="content-table">

    {% if data_sets %}
        <div class="content-table-title">
            <b class="title">Data sets</b>
            <form method="get" action="{% url 'schemas:generate' %}" class="form-inline float-right">
                {% csrf_token %}
                <div class="form-group mb-2">{{ form.rows.label_tag }}</div>
                <div class="form-group mx-sm-3 mb-2">{{ form.rows }}</div>
                <input class="btn btn-success mb-2" type="submit" value="Generate data">
            </form>
        </div>

        <table class="table table-bordered table-hover" >
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Created</th>
                    <th scope="col">Status</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for schema in data_sets %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{% url 'schemas:edit' schema.id %}">{{ schema.name }}</a></td>
                        <td>{{ schema.timestamp|date:"Y-m-d" }}</td>

                        {% if schema.csv_file %}
                            <td><button class="btn btn-success btn-sm" style="pointer-events: none"><b>Ready</b></button></td>
                            <td><a href="{% url 'schemas:download' schema.id %}">Download</a></td>
                        {% else %}
                            <td>
                                <div style="width: 75%;" id='progress-bar-{{ schema.id }}' class='progress-bar progress-bar-striped progress-bar-animated' role="progressbar">
                                    <div id="progress-bar-message-{{ schema.id }}">Waiting for start...</div>
                                </div>
                            </td>
                            <td id="celery-result-{{ schema.id }}"></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% include "pagination.html" with page_obj=page_obj %}
        <!-- Set 'celery-progress' progress bars.-->
        <script>
            {% for id, schema_id in task_ids %}
                document.addEventListener("DOMContentLoaded", function () {
                      var progressUrl = "{% url 'celery_progress:task_status' id %}";
                      CeleryProgressBar.initProgressBar(progressUrl, {
                        pollInterval: 4000,
                        onResult: customResult,
                        progressBarId: 'progress-bar-{{ schema_id }}',
                        progressBarMessageId: 'progress-bar-message-{{ schema_id }}',
                        resultElementId: 'celery-result-{{ schema_id }}',
                      })
                });
            {% endfor %}
        </script>
    {% else %}
        <b class="title">Data sets</b>
        <p>No Data sets available.</p>
        <a class="btn btn-primary" href="{% url 'schemas:create' %}">Create New Schema</a>
    {% endif %}
</div>
{% endblock %}

schemas/front/templates/pagination.html
<div class="pagination d-flex justify-content-center">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="btn btn-primary btn-sm" href="?page=1">&laquo; first</a>
            <a class="btn btn-primary btn-sm" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a class="btn btn-primary btn-sm" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="btn btn-primary btn-sm" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

schemas/front/templates/schemas.html
{% extends "base.html" %}
{% block content %}

<div id="schemas_list_wrapper" class="content-table">

    <div class="content-table-title">
        <b class="title">Data schemas</b>
        <form action="{% url 'schemas:create' %}" class="form-inline float-right">
            {% csrf_token %}
            <div class="form-group mb-2">{{ form.rows.label_tag }}</div>
            <div class="form-group mx-sm-3 mb-2">{{ form.rows }}</div>
            <input class="btn btn-success mb-2" type="submit" value="New schema">
        </form>
    </div>

    {% if schemas %}
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Modified</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for schema in schemas %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{% url 'schemas:edit' schema.id %}">{{ schema.name }}</a></td>
                        <td>{{ schema.timestamp|date:"Y-m-d" }}</td>
                        <td>
                            <div id="edit-button">
                                <a href="{% url 'schemas:edit' schema.id %}">Edit schema</a>
                            </div>
                            <div id="delete-button">
                                <a style="color: #D9534F;" href="{% url 'schemas:delete' schema.id %}">Delete</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        {% include "pagination.html" with page_obj=page_obj %}

    {% else %}
        <p>No schemas are available.</p>
    {% endif %}
  </div>
{% endblock %}